(function(g){'use strict';
 const cfg=g.HISTORY_API_CONFIG||{},personal=!/\/(teacher|board)\.html$/.test(location.pathname),storeKey='history-v42-'+(personal?'student':'teacher')+(cfg.gasUrl?':'+encodeURIComponent(cfg.gasUrl):''),pending=new Map();let ticket=null,clockOffset=0,frame=null,bridgeWindow=null,bridgeOrigin='',channel='';
 const persistent={get(){try{return personal?localStorage.getItem(storeKey):null}catch{return null}},set(s){try{if(personal){if(s?.role==='student'&&!s.testOnly&&s.rememberDevice===true)localStorage.setItem(storeKey,JSON.stringify(s));else localStorage.removeItem(storeKey)}}catch{}}};
 let session;try{session=JSON.parse(sessionStorage.getItem(storeKey)||persistent.get()||'null');if(session?.expiresAt&&Date.parse(session.expiresAt)<=Date.now()){session=null;sessionStorage.removeItem(storeKey);persistent.set(null)}}catch{session=null}
 const applyCopyright=x=>{const v=x?.copyright||x?.publicDisplay?.copyright||x?.authority3?.copyright;if(v&&g.HistoryCopyright)g.HistoryCopyright.apply(v)};
 const uuid=()=>crypto.randomUUID?crypto.randomUUID():Array.from(crypto.getRandomValues(new Uint8Array(20)),x=>x.toString(16).padStart(2,'0')).join('');
 function remember(s){const changed=session?.token!==s?.token||JSON.stringify(session?.context3)!==JSON.stringify(s?.context3);session=s;if(changed)sessionStorage.removeItem(storeKey+':pending');if(s)sessionStorage.setItem(storeKey,JSON.stringify(s));else{sessionStorage.removeItem(storeKey);sessionStorage.removeItem(storeKey+':pending')}if(!s?.testOnly)persistent.set(s);if(changed&&g.dispatchEvent&&typeof CustomEvent==='function')g.dispatchEvent(new CustomEvent('history-session-changed',{detail:{authenticated:!!s}}))}
 addEventListener('storage',e=>{if(personal&&e.key===storeKey&&!session?.testOnly){let s=null;try{s=JSON.parse(e.newValue||'null')}catch{}remember(s)}});
 const readActions=new Set(['cards.openings.list','cards.openings.read','student.records.read','teacher.records.read','teacher.records.student','teacher.records.csv','teacher.records.settings','teacher.board.read','student.state','rankings.read','portal.read','access.check','teacher.overview','teacher.student.cards','teacher.test.check','student.login','teacher.login','owner.recover','owner.overview','teacher.scope.read','teacher.devices.read','teacher.testSettings.read','session.logout']);
 function pendingRequest(action,payload,requestId){if(readActions.has(action))return{requestId:requestId||uuid(),clear(){}};let rows;try{rows=JSON.parse(sessionStorage.getItem(storeKey+':pending')||'[]')}catch{rows=[]}rows=rows.filter(r=>r.owner===session?.token);const fingerprint=JSON.stringify({action,payload}),old=rows.find(r=>r.fingerprint===fingerprint),id=requestId||old?.requestId||uuid();if(!old){rows.push({fingerprint,requestId:id,owner:session?.token});sessionStorage.setItem(storeKey+':pending',JSON.stringify(rows))}return{requestId:id,clear(){let current;try{current=JSON.parse(sessionStorage.getItem(storeKey+':pending')||'[]')}catch{current=[]}sessionStorage.setItem(storeKey+':pending',JSON.stringify(current.filter(r=>r.requestId!==id)))}}}
 function sendPending(){if(!bridgeWindow)return;for(const [callId,p]of pending)if(!p.sent){p.sent=true;bridgeWindow.postMessage({type:'history-api',channel,callId,request:p.request},bridgeOrigin)}}
 function bridge(req){return new Promise((resolve,reject)=>{if(!/^https:\/\/script\.google\.com\/macros\/s\/[\w-]+\/exec$/.test(cfg.gasUrl||'')){const e=Error('Code.gs TEST 웹앱의 /exec 주소를 config.js에 설정하거나 로컬 시험 서버로 열어 주세요.');e.code='CONFIG_REQUIRED';return reject(e)}if(!frame){channel=uuid();frame=document.createElement('iframe');frame.hidden=true;frame.src=cfg.gasUrl+'?page=bridge&channel='+encodeURIComponent(channel);document.body.append(frame)}const callId=uuid(),timeout=setTimeout(()=>{pending.delete(callId);reject(Error('연결 시간 초과: 허용 출처와 TEST 웹앱 배포 설정을 확인하세요.'))},20000);pending.set(callId,{request:req,sent:false,resolve:x=>{clearTimeout(timeout);resolve(x)},reject});sendPending()})}
 addEventListener('message',e=>{if(!frame||(!/^https:\/\/([\w-]+\.)?googleusercontent\.com$/.test(e.origin)&&e.origin!=='https://script.google.com'))return;const d=e.data;if(d?.channel!==channel)return;if(d.type==='history-bridge-ready'&&!bridgeWindow){bridgeWindow=e.source;bridgeOrigin=e.origin;sendPending();return}if(e.source!==bridgeWindow||e.origin!==bridgeOrigin)return;if(d.type==='history-api-result'&&pending.has(d.callId)){pending.get(d.callId).resolve(d.result);pending.delete(d.callId)}});
 async function transport(req){if(cfg.mode==='local'||['localhost','127.0.0.1'].includes(location.hostname)){const abort=new AbortController(),timer=setTimeout(()=>abort.abort(),20000);try{const r=await fetch('/api',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(req),signal:abort.signal});return await r.json()}finally{clearTimeout(timer)}}return bridge(req)}
 async function bootstrap(){const r=await transport({action:'public.bootstrap'});if(!r.ok)throw Error(r.message||r.code);ticket=r.data.ticket;clockOffset=r.data.serverNow-Date.now();applyCopyright(r.data);return r.data}
 async function request(action,payload={},opts={}){if(session?.context3&&['teacher','owner'].includes(session.role)&&(action.startsWith('teacher.')&&action!=='teacher.login'||['rankings.read','portal.read'].includes(action)))payload={...payload,context3:payload.context3||{...session.context3,schoolYear:payload.schoolYear||session.context3.schoolYear}};const owner=session?.token,scopeAtStart=JSON.stringify(session?.context3),authToken=opts.token||owner,record=pendingRequest(action,payload,opts.requestId),requestId=record.requestId;let error;for(let attempt=0;attempt<5;attempt++){try{if(!ticket||ticket.expiresAt<Date.now()+clockOffset+10000)await bootstrap();const r=await transport({action,payload,requestId,ticket,token:authToken});if(!action.endsWith('.login')&&(session?.token!==owner||JSON.stringify(session?.context3)!==scopeAtStart)){const changed=Error('로그인 계정이 변경되었습니다. 다시 확인하세요.');changed.code='SESSION_CHANGED';throw changed}if(r.ok){record.clear();applyCopyright(r.data);return r.data}if(r.code==='REQUEST_EXPIRED'){ticket=null;continue}if(['BUSY','CONNECTION_ERROR','SERVER_ERROR'].includes(r.code))throw Error(r.message);const e=Error(r.message||r.code);e.code=r.code;throw e}catch(e){error=e;if(e.code){record.clear();if(['SESSION_EXPIRED','AUTH_REQUIRED','SESSION_REVOKED','ACCESS_DENIED'].includes(e.code)&&session?.token===owner)remember(null);break}if(attempt<4)await new Promise(r=>setTimeout(r,450*2**attempt+Math.random()*300))}}if(error?.code)throw error;const connection=Error('서버에 연결하지 못했습니다. 연결을 확인한 뒤 같은 작업을 다시 시도해 주세요.');connection.code='CONNECTION_ERROR';throw connection}
 g.HistoryGameAPI={version:'4.2',get session(){return session},request,bootstrap,async login(role,p){const result=await request(role+'.login',p);remember(result);return result},async logout(){try{await request('session.logout')}finally{remember(null)}},clear:()=>remember(null),resolveRequest(requestId){let rows;try{rows=JSON.parse(sessionStorage.getItem(storeKey+':pending')||'[]')}catch{rows=[]}sessionStorage.setItem(storeKey+':pending',JSON.stringify(rows.filter(r=>r.owner!==session?.token||r.requestId!==requestId)))},saveSession:remember,newRequestId:uuid};
})(window);
