/* v4.1: adapters around the actual v4.0 gameplay, not REVIEW04 demo games. */
const CollectionRefs41={1:['fr-revolution','FR-01'],2:['fr-revolution','FR-02'],3:['fr-revolution','FR-03'],4:['fr-revolution','FR-04'],5:['fr-revolution-supplement','FR-X05'],6:['fr-revolution','FR-05'],7:['fr-revolution','FR-06'],8:['fr-revolution-supplement','FR-X08'],9:['fr-revolution','FR-07'],10:['fr-revolution','FR-08'],11:['fr-revolution','FR-09'],12:['fr-revolution','FR-10'],13:['fr-revolution','FR-11'],14:['fr-revolution','FR-12']};
const ref41=([unitId,eventId])=>({unitId,eventId});
const collectionRef41=id=>ref41(CollectionRefs41[id]);
const questionRef41=id=>({unitId:'fr-revolution',eventId:'FR-'+String(id).padStart(2,'0')});
const event41=ref=>HistoryContent.event(ref.unitId,ref.eventId);
// Numeric question and inventory IDs remain unchanged. Content is resolved through getters.
for(const q of Q){const ref=questionRef41(q.id);q.contentRef=ref;Object.defineProperties(q,{title:{get:()=>event41(ref).title,configurable:true},prompt:{get:()=>event41(ref).gameplayV40.prompt,configurable:true},a:{get:()=>event41(ref).gameplayV40.acceptedAnswers,configurable:true}});Object.defineProperty(DESC,q.id,{get:()=>event41(ref).shortDescription,configurable:true});}
for(const c of CH){const ref=collectionRef41(c.id);c.contentRef=ref;Object.defineProperty(c,'title',{get:()=>event41(ref).title,configurable:true});Object.defineProperty(IMAGES,c.img-1,{get:()=>HistoryContent.image(event41(ref)),configurable:true});}
const imageSrcV41=i=>IMAGES[i];imageSrcV40=imageSrcV41;
window.GameAPI=HistoryGameAPI;GAME_API_V37.endpoint='';GAME_API_V37.call=(action,data)=>HistoryGameAPI.request(action,data);
// No student records, statistics or rewards are sent to a live server during review.
flushOutbox=()=>showSync();scheduleSync=()=>{};jsonp=(_url,done)=>done({ok:false,code:'LOCAL_REVIEW'});
loadProfileInfo=(_p,done)=>done(null);loadRanking=loadRankingV26=()=>{rankData={ranking:[]};rankError='로컬 검토판: 서버 랭킹은 연결하지 않았습니다.';if(RANKING)renderV41()};
syncLabel=()=>PreviewStorageStatus41().persistent?'v4.1 · 이 기기에만 저장 · 서버 미연결':'저장 불가 · 기록을 내보내 주세요';
showSync=()=>{const el=document.querySelector('.sync');if(el){el.textContent=syncLabel();el.title='로컬 검토본입니다. 서버 저장 또는 보안 검증 완료를 뜻하지 않습니다.';el.onclick=exportLocal41}};
manualSync=()=>alert('이 버전은 기존 서버에 접속하지 않습니다. 승인 후 Code.gs를 연결합니다.');
function exportLocal41(){const data=HistoryGameAPI.exportLocal(),url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download='fr-v4.1-local-backup-'+new Date().toISOString().slice(0,10)+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),2000)}
function previewTeacher41(){if(!confirm('교사용 로컬 시험 기능을 여시겠습니까? 실제 인증이 아니며 이 기기의 시험 사본에만 적용됩니다.'))return;teacherUnlocked=true;PreviewSession41.setItem('fr-teacher-v1','1');view='admin';renderV41()}
teacherMenu=previewTeacher41;
setProfile=function(p){profile={...p,schoolYear:Number(p.schoolYear)||new Date().getFullYear(),serverBest:0};PreviewStore41.setItem('fr-student-v2',JSON.stringify(profile));try{P=JSON.parse(PreviewStore41.getItem(key()))||fresh()}catch{P=fresh()}practice={mode:null,state:null};speed=null;bait=null;matchGame=null;dailyChecked=false;view='beginner';renderV41();clock();bonusClock()};
const profileScreen41Base=profileScreen;
profileScreen=function(){profileScreen41Base();document.title='프랑스 혁명 학습 게임 v4.1';document.querySelector('.version').textContent='v4.1';document.querySelector('.registry-note').textContent='로컬 검토판 · 기존 기록은 읽되 수정은 별도 시험 사본에 저장합니다. 서버로 전송하지 않습니다.'};
function escape41(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
let collectionTier41='normal',acquiredCache41=null;
function cardData41(id,rarity,count){const ref=collectionRef41(id),data=HistoryContent.toCard(ref.unitId,ref.eventId,{rarity,ownedCount:count,firstAcquiredAt:(acquiredCache41||loadAcquiredV33())[id+'-'+rarity]||''});if(ref.unitId==='fr-revolution-supplement'){data.previousEvent=id===5?'바스티유 감옥 습격':'루이 16세의 탈출 실패';data.nextEvent=id===5?'인권 선언':'공화정 수립';data.detailedDescription=[{heading:'배경·전개·의미',text:CARD_DETAIL_V39[id]}]}return data}
function collectionMarkup41(id,rarity,count,mode='list'){return renderHistoryCard(cardData41(id,rarity,count),{mode}).replace(/decoding="async"/g,'decoding="async" loading="'+(mode==='list'?'lazy':'eager')+'"')}
collectCard=function(event,rar,count,locked=false,interactive=true){if(locked)return `<article class="hc-locked41" aria-label="${rar.name} 미획득 카드"><img src="${HistoryCards.frameURL(rar.id)}" alt="" loading="lazy" decoding="async"><strong>미획득</strong><span>${rar.name}</span></article>`;return `<div class="hc-entry41" ${interactive?`role="button" tabindex="0" aria-label="${escape41(event.title)} 확대" onclick="inspectCard(event,${event.id},'${rar.id}',${count})" onkeydown="if(event.key==='Enter'||event.key===' '){event.preventDefault();inspectCard(event,${event.id},'${rar.id}',${count})}"`:''}>${collectionMarkup41(event.id,rar.id,count,interactive?'list':'reveal')}</div>`};
collectionBookV34=function(){const c=loadCollection(),owned=Object.values(c).filter(n=>n>0).length,r=rarityById(collectionTier41);acquiredCache41=loadAcquiredV33();return `<div class="practicebar"><div><p class="eyebrow">공통 역사 카드 시스템</p><h2>카드 도감 ${owned}/70</h2></div><span class="pill">기존 14사건·5등급 보존</span></div><p>카드를 눌러 확대하고, 확대된 카드를 다시 누르면 뒤집힙니다.</p><div class="tier-tabs41">${RARITIES.map(t=>`<button class="${t.id===r.id?'on':''}" onclick="collectionTier41='${t.id}';renderV41()">${t.name} <small>${CH.filter(e=>(c[e.id+'-'+t.id]||0)>0).length}/14</small></button>`).join('')}</div><div class="collectiongrid v41-grid">${CH.map(e=>collectCard(e,r,c[e.id+'-'+r.id]||0,!(c[e.id+'-'+r.id]>0))).join('')}</div>`};
inspectCard=function(e,id,rarityId,count){e?.stopPropagation?.();cardInspect={event:CH.find(x=>x.id===id),rar:rarityById(rarityId),count,flipped:false};renderV41();document.querySelector('.inspectclose')?.focus()};
cardInspectModal=function(){if(!cardInspect)return '';const x=cardInspect;return `<div class="cardinspect v41-inspect" role="dialog" aria-modal="true" aria-label="${escape41(x.event.title)} 카드 확대" onclick="closeInspect41()"><div class="inspectpanel v41-inspect-panel" onclick="event.stopPropagation()"><button class="inspectclose" onclick="closeInspect41()" aria-label="닫기">×</button>${collectionMarkup41(x.event.id,x.rar.id,x.count,'detail')}<p class="inspecttip">카드를 누르면 앞·뒷면이 전환됩니다.</p></div></div>`};
function closeInspect41(){cardInspect=null;renderV41()}
const quiz41Base=quiz,practiceQuiz41Base=practiceQuiz;
function questionPicture41(q){const e=event41(q.contentRef),f=HistoryContent.focal(e,'game');return `<div class="question-picture41"><img src="${HistoryContent.image(e)}" alt="사건 그림" decoding="async" style="object-position:${f.x}% ${f.y}%"></div>`}
quiz=function(m){let h=quiz41Base(m);if(m==='intermediate'&&P[m].status==='active'){const q=Q.find(q=>q.id===P[m].sequence[P[m].pos]);h=h.replace(/<img class="qimg"[^>]*>/,questionPicture41(q))}return h};
practiceQuiz=function(){let h=practiceQuiz41Base();if(practice.mode==='intermediate'){const q=Q.find(q=>q.id===practice.state.sequence[practice.state.pos]);h=h.replace(/<img class="qimg"[^>]*>/,questionPicture41(q))}return h};
function gameCard41(it,attrs='',variant='full'){return renderHistoryGameCard(it.contentRef||it,{variant}).replace('<button type="button"','<button type="button" '+attrs)}
function gameInside41(it,variant='full'){return gameCard41(it,'',variant).replace(/^<button[^>]*>/,'<span class="history-game-card" aria-hidden="true">').replace(/<\/button>$/,'</span>')}
card=function(m,id,items){return gameCard41(items.find(x=>x.id===id),`data-drag-mode="${m}" data-drag-id="${id}" class-placeholder="" draggable="true" onclick="cardClick('${m}',${id})" ondblclick="cardDouble(event,'${m}',${id})" ondragstart="dragStart(event,'${m}',${id})" ondragend="dragEnd()"`).replace('aria-pressed="false"',`aria-pressed="${P[m].selected===id}"`)};
slot=function(m,id,i,items){const s=P[m],cl=id?'filled':'',judge=s.checked&&id?(id===i+1?'ok':'bad'):'';return `<div class="slot game-slot41 ${cl} ${judge}" data-drop-mode="${m}" data-drop-index="${i}" data-drag-mode="${m}" data-drag-id="${id||''}" draggable="${!!id}" role="button" tabindex="0" onclick="slotClick('${m}',${i})" onkeydown="if(event.key==='Enter')slotClick('${m}',${i})" ondblclick="slotDouble(event,'${m}',${i})" ondragstart="dragStart(event,'${m}',${id||'null'})" ondragover="event.preventDefault()" ondrop="dropSlot(event,'${m}',${i})"><span class="num">${i+1}</span>${id?gameInside41(items.find(x=>x.id===id))+`<button class="remove" aria-label="카드 되돌리기" onclick="event.stopPropagation();removeSlot('${m}',${i})">×</button>`:'＋'}</div>`};
bonusCard=function(kind,id,items){return gameCard41(items.find(x=>x.id===id),`data-drag-mode="bonus:${kind}" data-drag-id="${id}" draggable="true" onclick="bonusCardClick('${kind}',${id})" ondblclick="bonusCardDouble(event,'${kind}',${id})" ondragstart="bonusDragStart(event,'${kind}',${id})" ondragend="dragEnd()"`).replace('aria-pressed="false"',`aria-pressed="${bonusState(kind).selected===id}"`)};
bonusSlot=function(kind,id,i,items){const s=bonusState(kind);return `<div class="slot game-slot41 ${id?'filled':''} ${s.checked&&id?(id===i+1?'ok':'bad'):''}" data-drop-mode="bonus:${kind}" data-drop-index="${i}" data-drag-mode="bonus:${kind}" data-drag-id="${id||''}" role="button" tabindex="0" draggable="${!!id}" onclick="bonusSlotClick('${kind}',${i})" onkeydown="if(event.key==='Enter')bonusSlotClick('${kind}',${i})" ondblclick="bonusSlotDouble(event,'${kind}',${i})" ondragstart="bonusDragStart(event,'${kind}',${id||'null'})" ondragover="event.preventDefault()" ondrop="bonusDrop(event,'${kind}',${i})"><span class="num">${i+1}</span>${id?gameInside41(items.find(x=>x.id===id))+`<button class="remove" aria-label="카드 되돌리기" onclick="event.stopPropagation();bonusRemove('${kind}',${i})">×</button>`:'＋'}</div>`};
// Preserve v4.0's 12-target chronological bait-run and 4/6/8-decoy choices.
startBait=function(n){if(![4,6,8].includes(n))return;const units=['uk-revolution','us-revolution'];const decoys=units.flatMap(unit=>shuffle(HistoryContent.foreignDecoys('fr-revolution',[unit]).filter(r=>!HistoryContent.unit('fr-revolution').modes?.decoy?.excludedRefs?.some(x=>typeof x==='string'?x===r.unitId+'/'+r.eventId:x.unitId===r.unitId&&x.eventId===r.eventId))).slice(0,n/2));const refs=Object.fromEntries(decoys.map(r=>[r.unitId+'/'+r.eventId,{unitId:r.unitId,eventId:r.eventId}]));bait={status:'active',decoyCount:n,refs,deck:shuffle(Q.map(q=>'f'+q.id).concat(Object.keys(refs))),slots:Array(Q.length).fill(null),selected:null,checked:false,errorChecks:0,startedAt:performance.now(),finishedMs:0,official:n===8};renderV41();bonusClock()};
function baitRef41(id){return id.startsWith('f')?questionRef41(+id.slice(1)):bait.refs[id]}
baitInfo=function(id){const ref=baitRef41(id);return {...event41(ref),contentRef:ref,french:id.startsWith('f')}};
baitCard=function(id){return gameCard41(baitRef41(id),`data-drag-mode="bait" data-drag-id="${id}" draggable="true" onclick="baitSelect('${id}')" ondblclick="baitAuto(event,'${id}')" ondragstart="event.dataTransfer.setData('text/plain','${id}')"`).replace('aria-pressed="false"',`aria-pressed="${bait.selected===id}"`)};
baitSlot=function(id,i){return `<div class="slot game-slot41 ${id?'filled':''} ${bait.checked&&id?(id==='f'+(i+1)?'ok':'bad'):''}" data-drop-mode="bait" data-drop-index="${i}" data-drag-mode="bait" data-drag-id="${id||''}" role="button" tabindex="0" onclick="baitPlace(${i})" onkeydown="if(event.key==='Enter')baitPlace(${i})" ondblclick="baitRemove(event,${i})" ondragover="event.preventDefault()" ondrop="baitDrop(event,${i})"><span class="num">${i+1}</span>${id?gameInside41(baitRef41(id)):'＋'}</div>`};
// Basic = identical cards; advanced = picture/title against description, as in v4.0.
matchCard=function(c,i){const open=matchGame.open.includes(i)||matchGame.done.includes(i),done=matchGame.done.includes(i),description=matchGame.variant==='advanced'&&c.side===1;return `<button class="matchcard match41 ${open?'open':''} ${done?'done':''}" onclick="flipMatch(${i})" aria-label="${open?escape41(description?'사건 설명':c.q.title):'뒤집힌 카드'}">${!open?'<span class="matchback">?</span>':description?`<span class="match-description41">${escape41(DESC[c.q.id])}</span>`:gameInside41(c.q)}</button>`};
faceGrid=function(ids,interactive){return `<div class="memorygrid">${ids.map((id,i)=>gameCard41(Q.find(q=>q.id===id),interactive?`onclick="facePick(${i})"`:'disabled')).join('')}</div>`};
const packAsset41=id=>(window.HISTORY_PACK_ASSETS||{})[id]||'assets/packs/history-pack-back-'+id+'.png';
// A guaranteed pack must not be promoted by the cross-pack pity counter.
// Random pack probabilities, counters and the original fusion rules are unchanged.
const drawPackV41Base=drawPackCardV36;
drawPackCardV36=function(packId,collection,minIndex=0){const p=packByIdV36(packId);if(!p.fixed)return drawPackV41Base(packId,collection,minIndex);const rar=rarityById(p.id),event=CH[Math.floor(Math.random()*CH.length)],key=event.id+'-'+rar.id;collection[key]=(collection[key]||0)+1;const st=loadPackPityV36();st.sinceMyth=rar.id==='myth'?0:Number(st.sinceMyth||0)+1;savePackPityV36(st);return {event,rar,count:collection[key],isNew:collection[key]===1}};
packBackV36=function(p,compact=false){return `<div class="packitem"><img class="pack-png41" src="${packAsset41(p.id)}" alt="${p.name}" loading="lazy" decoding="async">${compact?'':`<h4>${p.name}</h4><small>${p.note}</small>`}</div>`};
let revealToken41=0,revealTimer41=null;
function packStage41(p,x,shown){return `<div class="stage v41-stage" data-pack="${p.id}" data-state="${shown?'revealed':'sealed'}"><div class="pack-aura" aria-hidden="true">${'<i></i>'.repeat(6)}</div><div class="result-slot" ${shown?'':'inert'}>${shown?collectionMarkup41(x.event.id,x.rar.id,x.count,'reveal'):''}</div>${shown?'':`<button class="sealed-pack" onclick="revealPack(${packReward.cursor})" aria-label="${p.name} 개봉"><span class="pack-piece pack-piece--left"><img src="${packAsset41(p.id)}" alt="" draggable="false"></span><span class="pack-piece pack-piece--right"><img src="${packAsset41(p.id)}" alt="" draggable="false"></span><span class="pack-shine"></span></button>`}<div class="opening-flash" aria-hidden="true"></div></div>`}
packResultCardV39=function(x){return `<div class="result-card41">${collectionMarkup41(x.event.id,x.rar.id,x.count,'list')}${x.isNew?'<b class="new41">NEW</b>':''}</div>`};
rewardModal=function(){if(!packReward)return '';normalizePackRewardV38();const p=packByIdV36(packReward.packType),i=packReward.cursor,total=packReward.cards.length;if(packReward.phase==='done'||i>=total){const sums=Object.fromEntries(RARITIES.map(r=>[r.id,0]));packReward.cards.forEach(x=>sums[x.rar.id]++);return `<div class="rewardmodal v41-reward" role="dialog" aria-modal="true" aria-label="개봉 결과"><div class="packbox v41-packbox"><h2>개봉 완료 · ${total}장</h2><div class="packresults41">${packReward.cards.map(packResultCardV39).join('')}</div><div class="packsummary38">${RARITIES.map(r=>`<span>${r.name}<b>${sums[r.id]}</b></span>`).join('')}</div><button class="btn" onclick="closePackV38()">확인 · 닫기</button></div></div>`}const x=packReward.cards[i],shown=packReward.phase==='shown';return `<div class="rewardmodal v41-reward" role="dialog" aria-modal="true" aria-label="카드팩 개봉"><div class="packbox v41-packbox"><h2>${p.name}</h2><p class="packprogress38">${i+1} / ${total} · ${shown?x.rar.name+' 카드 등장!':'가운데 팩을 눌러 개봉하세요'}</p>${packStage41(p,x,shown)}<div class="packcontrols39"><button class="btn alt" onclick="closePackV38()">닫기</button>${shown?`<button class="btn" onclick="advancePackV38()">${i+1===total?'결과 확인':'확인 · 다음 카드'}</button>`:''}${total>1?`<button class="btn alt" onclick="autoOpenPackV39()">${packAutoV38?'자동 개봉 중지':'한 장씩 자동 개봉'}</button><button class="btn" onclick="revealAllPackV39()">모두 동시 개봉</button>`:''}</div><small class="pack-status41">${shown?'카드를 누르면 상세 설명을 볼 수 있습니다.':'닫아도 이미 획득한 결과는 도감에 보관됩니다.'}</small></div></div>`};
revealPack=async function(i){normalizePackRewardV38();if(!packReward||packReward.phase!=='covered'||i!==packReward.cursor)return;const token=++revealToken41,current=packReward,x=current.cards[i],stage=document.querySelector('.v41-stage');current.phase='opening';clearTimeout(packAutoTimerV38);stage?.querySelector('.sealed-pack')?.setAttribute('disabled','');const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;try{await Promise.all([readyAsset41(HistoryCards.frameURL(x.rar.id)),readyAsset41(cardData41(x.event.id,x.rar.id,x.count).image)])}catch{if(token!==revealToken41||packReward!==current)return;current.phase='covered';renderV41();alert('그림을 불러오지 못했습니다. 파일 구성을 확인하고 다시 개봉해 주세요.');return}if(token!==revealToken41||packReward!==current)return;stage.dataset.state='opening';revealTimer41=setTimeout(()=>{if(token!==revealToken41||packReward!==current)return;stage.dataset.state='splitting';const slot=stage.querySelector('.result-slot');slot.innerHTML=collectionMarkup41(x.event.id,x.rar.id,x.count,'reveal');revealTimer41=setTimeout(()=>{if(token!==revealToken41||packReward!==current)return;current.phase='shown';current.revealed=i+1;current.lastReveal=i;renderV41()},reduced?60:490)},reduced?50:640)};
const assetReady41=new Map();function readyAsset41(url){if(!assetReady41.has(url))assetReady41.set(url,new Promise((resolve,reject)=>{const image=new Image();image.onload=()=>resolve();image.onerror=()=>{assetReady41.delete(url);reject(Error('image load'))};image.src=url}));return assetReady41.get(url)}
advancePackV38=function(){if(!packReward||packReward.phase!=='shown')return;const current=packReward,token=++revealToken41;current.phase='leaving';document.querySelector('.result-slot')?.classList.add('leaving41');clearTimeout(packAutoTimerV38);revealTimer41=setTimeout(()=>{if(packReward!==current||token!==revealToken41)return;current.cursor++;current.phase=current.cursor>=current.cards.length?'done':'covered';renderV41()},matchMedia('(prefers-reduced-motion: reduce)').matches?0:300)};
closePackV38=function(){revealToken41++;clearTimeout(revealTimer41);clearTimeout(packAutoTimerV38);packAutoV38=false;packReward=null;renderV41()};
autoOpenPackV39=function(){if(!packReward)return;packAutoV38=!packAutoV38;clearTimeout(packAutoTimerV38);if(['covered','shown'].includes(packReward.phase))renderV41()};
revealAllPackV39=function(){if(!packReward)return;revealToken41++;clearTimeout(revealTimer41);clearTimeout(packAutoTimerV38);packAutoV38=false;packReward.phase='done';packReward.cursor=packReward.cards.length;packReward.revealed=packReward.cards.length;renderV41()};
schedulePackAutoV38=function(){clearTimeout(packAutoTimerV38);if(!packAutoV38||!packReward)return;const phase=packReward.phase;if(!['covered','shown'].includes(phase))return;packAutoTimerV38=setTimeout(()=>phase==='covered'?revealPack(packReward.cursor):advancePackV38(),phase==='covered'?520:1050)};
// Keep admin content/settings; label server functionality accurately.
const adminPage41Base=adminPage;
adminPage=function(){return adminPage41Base().replace(/v3\.[0-9]/g,'v4.1').replace('기존 Apps Script 기록 전송 유지','서버 전송 중지 · 로컬 시험 사본').replace('서버 교체 가능한 공통 통신층 준비됨','서버 미연결 · 보안 판정은 승인 후 구현')};
function shell41(body){const open=coreComplete()||teacherUnlocked,tabs=['beginner','intermediate','advanced','bonus','collection','results',...(teacherUnlocked?['admin']:[])];return `<header class="header"><div class="headerin"><div><p class="eyebrow">1789 — 1799</p><h1>프랑스 혁명 학습 게임 <span class="version">v4.1</span></h1></div><div class="student"><span>${profile.schoolYear}학년도 · ${escape41(profile.grade)}학년 ${escape41(profile.classNo)}반 ${escape41(profile.number)}번 ${escape41(profile.name)}</span><button class="btn alt" onclick="profileScreen()">학생 정보 변경</button></div></div></header><main class="wrap"><div class="local-notice41">로컬 통합 검토판 · 서버 미연결 · 기존 기록과 분리 저장 <button onclick="exportLocal41()">시험 기록 내보내기</button></div><nav class="tabs">${tabs.map(m=>{const lock=['intermediate','advanced'].includes(m)&&!unlockedV28(m)||m==='bonus'&&!open;return `<button class="tab ${view===m?'active':''} ${lock?'locked':''}" onclick="go('${m}')">${names[m]||({bonus:'보너스 게임',collection:'카드 도감',results:'결과',admin:'교사 관리'})[m]}${P[m]?.status==='completed'?' ✓':lock?' 🔒':''}</button>`}).join('')}</nav>${body}</main><div class="sync" role="button" tabindex="0" onclick="exportLocal41()">${syncLabel()}</div>${themeBadgeV35()}${rewardModal()}${cardInspectModal()}`}
function renderV41(){acquiredCache41=null;if(RANKING){rankError='로컬 검토판: 서버 랭킹 연결은 승인 후 진행합니다.';rankStarted=true;rankingScreenV26();return}if(!profile){profileScreen();return}const open=coreComplete()||teacherUnlocked;if(['bonus','practice','speedrun','baitrun','matching','faceoff'].includes(view)&&!open)view='results';if(view==='admin'&&!teacherUnlocked)view='results';if(['beginner','intermediate','advanced'].includes(view)&&!unlockedV28(view))view='beginner';const body=view==='beginner'||view==='intermediate'?quiz(view):view==='advanced'||view==='challenge'?order(view):view==='bonus'?bonusHub():view==='collection'?collectionPage():view==='practice'?practicePageV28():view==='speedrun'?speedPageV28():view==='baitrun'?baitPage():view==='matching'?matchingPage():view==='faceoff'?facePage():view==='admin'?adminPage():resultsV29();app.innerHTML=shell41(body).replaceAll('마스터 코드 입력','교사 기능 시험').replaceAll('전광판과 수업용 전체 해금은 마스터 코드가 필요합니다.','로컬 시험용입니다. 실제 교사 인증과 전광판은 서버 연결 후 사용할 수 있습니다.');document.title='프랑스 혁명 학습 게임 v4.1';for(const root of document.querySelectorAll('.v41-inspect,.v41-reward'))HistoryCards.mountHistoryCards(root);document.querySelectorAll('.hc-entry41 .history-card').forEach(c=>c.removeAttribute('tabindex'));if(cardInspect?.flipped){const c=document.querySelector('.v41-inspect .history-card');if(c)HistoryCards.flipHistoryCard(c,true)}document.querySelector('.v41-inspect')?.addEventListener('historycardflip',e=>{if(cardInspect)cardInspect.flipped=e.detail.back});showSync();if(view==='admin'){if(adminView==='gift'){syncGiftTarget();syncGiftModeV38()}if(adminView==='records')syncDeleteFieldsV37()}requestAnimationFrame(()=>document.querySelector('#ans')?.focus({preventScroll:true}));schedulePackAutoV38();if(!dailyChecked)setTimeout(maybeDailyPack,0)}
// All old action callbacks use the same renderer (no repeated full DOM re-parsing).
render=renderV28=renderV29=renderV30=renderV31=renderV32=renderV33=renderV34=renderV35=renderV36=renderV37=renderV38=renderV39=renderV40=renderV41;
for(const install of [installV37Style,installV38Style,installV39Style,installV40Style])install();
// Keep integration styles last after the preserved legacy style installers.
document.querySelector('#integration-style41')?.remove();const styles41=document.querySelector('[data-integration-style]');if(styles41)document.head.appendChild(styles41);
document.addEventListener('keydown',e=>{if(e.key==='Escape'){if(cardInspect)closeInspect41();else if(packReward)closePackV38()}if(e.key==='Tab'){const modal=document.querySelector('.v41-inspect')||document.querySelector('.v41-reward');if(!modal)return;const nodes=[...modal.querySelectorAll('button:not([disabled]),[tabindex="0"]')].filter(n=>n.getClientRects().length&&!n.closest('[inert]'));const first=nodes[0],last=nodes.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus()}}});
// Touch long-press drag; ordinary taps and page scrolling remain available.
let touch41=null,suppressClick41=0;
document.addEventListener('pointerdown',e=>{if(e.pointerType!=='touch'||e.target.closest('.remove'))return;const el=e.target.closest('[data-drag-mode][data-drag-id]');if(!el?.dataset.dragId)return;touch41={el,mode:el.dataset.dragMode,id:el.dataset.dragId,x:e.clientX,y:e.clientY,pointer:e.pointerId,active:false};touch41.timer=setTimeout(()=>{if(!touch41)return;touch41.active=true;touch41.ghost=el.cloneNode(true);touch41.ghost.classList.add('drag-ghost41');touch41.ghost.style.cssText=`width:${el.getBoundingClientRect().width}px;left:${touch41.x}px;top:${touch41.y}px`;document.body.appendChild(touch41.ghost)},220)});
document.addEventListener('pointermove',e=>{if(!touch41||e.pointerId!==touch41.pointer)return;const d=touch41;if(!d.active){if(d.scrolling||Math.hypot(e.clientX-d.x,e.clientY-d.y)>10){clearTimeout(d.timer);d.scrolling=true;e.preventDefault();scrollBy(0,(d.lastY??d.y)-e.clientY);d.lastY=e.clientY}return}e.preventDefault();d.ghost.style.left=e.clientX+'px';d.ghost.style.top=e.clientY+'px';if(e.clientY<80)scrollBy(0,-14);if(e.clientY>innerHeight-80)scrollBy(0,14)},{passive:false});
function endTouch41(e,cancel){if(!touch41)return;const d=touch41;clearTimeout(d.timer);touch41=null;d.ghost?.remove();if(d.scrolling)suppressClick41=Date.now()+550;if(!d.active)return;suppressClick41=Date.now()+550;if(cancel)return;const slot=document.elementFromPoint(e.clientX,e.clientY)?.closest('[data-drop-mode]');if(!slot||slot.dataset.dropMode!==d.mode)return;const i=+slot.dataset.dropIndex;if(d.mode==='bait'){bait.selected=d.id;baitPlace(i)}else if(d.mode.startsWith('bonus:')){const kind=d.mode.slice(6);bonusState(kind).selected=+d.id;bonusPlace(kind,i)}else{P[d.mode].selected=+d.id;place(d.mode,i)}}
document.addEventListener('pointerup',e=>endTouch41(e,false));document.addEventListener('pointercancel',e=>endTouch41(e,true));document.addEventListener('click',e=>{if(Date.now()<suppressClick41){e.preventDefault();e.stopImmediatePropagation()}},true);
// v4.2 authenticated entry point lives in student-v42.js.
window.V41={version:'4.1',collectionRef:collectionRef41,questionRef:questionRef41,render:renderV41,exportLocal:exportLocal41,storageStatus:PreviewStorageStatus41};
