/* Shared presentation helpers. Values and eligibility are always server projections. */
(function(g){'use strict';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const date=v=>v?new Date(v).toLocaleString('ko-KR',{timeZone:'Asia/Seoul',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'}):'기록 없음';
const pct=v=>v===null||v===undefined?'집계 불가':(v*100).toFixed(1)+'%';
const ms=v=>typeof v==='number'&&v>0?(v/1000).toFixed(2)+'초':'기록 없음';
const flag=v=>v===null||v===undefined?'집계 불가':v?'완료':'미완료';
function table(heads,rows){return`<div class="r27-tablewrap"><table><thead><tr>${heads.map(h=>`<th>${esc(h)}</th>`).join('')}</tr></thead><tbody>${rows.length?rows.map(r=>`<tr>${r.map(v=>`<td>${v??''}</td>`).join('')}</tr>`).join(''):`<tr><td colspan="${heads.length}">기록 없음</td></tr>`}</tbody></table></div>`}
function stat(label,value){return`<article class="r27-stat"><span>${esc(label)}</span><strong>${esc(value)}</strong></article>`}
function games(rows){return table(['게임·조건','시작 / 정상 완료','중단 / 포기','정상 완료 최고','공식 최고기록','최근 정상 완료','평균 정상 완료'],rows.map(r=>[esc(r.label),(r.started===null?'집계 불가':r.started)+' / '+r.completed,(r.paused===null?'집계 불가':r.paused)+' / '+r.abandoned,ms(r.personalBest?.elapsedMs),ms(r.best?.elapsedMs),ms(r.latest?.elapsedMs)+'<small>'+date(r.latest?.at)+'</small>',ms(r.averageMs)]))+'<p class="r27-note">연습·검토 기록은 정상 완료·평균·최고기록에서 제외됩니다. 미끼런 공식 순위는 기존 8장 조건, 짝맞추기는 고급 12세트 조건을 유지합니다. 과거 중단 횟수는 상세 이력이 없으면 집계할 수 없습니다.</p>'}
function attempts(rows){return table(['게임','분류','시각','시간','사유'],rows.map(r=>[esc(r.label),esc(r.classificationLabel),date(r.statusAt),ms(r.elapsedMs),esc(r.reason||r.coverage)]))}
function rewards(rows){return table(['구분','시각','실제 지급 결과'],rows.map(r=>[esc(r.kind),date(r.at),esc(r.message||'집계 불가')]))}
function learning(d){const s=d.summary;return`<div class="r27-stats">${stat('누적 성공',s.mastered+' / 60')}${stat('오늘 성공',s.todaySuccess+' / 60')}${stat('초급 유형',s.beginner+' / 24')}${stat('중급 유형',s.intermediate+' / 36')}</div><div class="r27-notice">오늘의 기본 복습: 초급 ${flag(s.basic.beginner)} · 중급 ${flag(s.basic.intermediate)}<br>오늘의 완전 숙련: ${flag(s.fullToday)}${s.masteryUnknown?'<br>이전 일부 숙련의 근거가 없어 집계 불가 항목이 있습니다.':''}</div><h3>유형별 누적 숙련</h3>${table(['유형','확인된 성공 / 12'],[1,2,3,4,5].map(t=>{const qs=s.questions.filter(q=>q.type===t);return[esc(qs[0]?.typeLabel||''),qs.filter(q=>q.confirmed===true).length+'/12'+(qs.some(q=>q.confirmed===null)?' · 일부 집계 불가':'')]}))}<h3>사건을 눌러 5개 유형을 확인하세요</h3><div class="r27-events">${d.events.map(e=>`<details><summary><span>${esc(e.title)}</span><b>${e.success}/5${e.questions.some(q=>q.confirmed===null)?' · 일부 집계 불가':''}</b></summary>${table(['유형','상태','최근 학습'],e.questions.map(q=>[esc(q.typeLabel),`숙련 ${flag(q.confirmed)}<small>오늘 ${flag(q.today)} · 경험 ${q.seen===null?'집계 불가':q.seen?'있음':'없음'}<br>정답 응답 ${flag(q.answeredCorrect)}<br>2회 오답 넘김 ${flag(q.skipped)} · 재도전 성공 ${flag(q.retrySuccess)}</small>`,date(q.lastStudiedAt)]))}</details>`).join('')}</div><h3>최근 틀린 문항</h3>${table(['사건·유형','최근 오답'],s.questions.filter(q=>q.lastWrongAt).sort((a,b)=>b.lastWrongAt.localeCompare(a.lastWrongAt)).slice(0,12).map(q=>[esc(q.title+' · '+q.typeLabel),date(q.lastWrongAt)]))}<p class="r27-note">${esc(d.formulas.mastery)}</p>`}
function xp(d){const s=d.summary;return`<div class="r27-stats">${stat('현재 레벨','Lv. '+s.level)}${stat('누적 XP',s.xp)}${stat('다음 레벨까지',s.nextXP===null?'최고 레벨':s.nextXP+' XP')}${stat('조회 기간 XP',s.periodXP)}</div><h3>최근 경험치</h3>${table(['시각','게임','획득 XP','현재 집계'],d.xp.map(r=>[date(r.at),esc(r.game),r.amount+' XP',r.eligible?'정상':'기록 제외·지급 이력 보존']))}<h3>레벨 상승과 실제 보상</h3>${table(['시각','레벨','실제 보상'],d.levels.map(r=>[date(r.at),r.previousLevel+' → '+r.level,esc(r.rewards.length?r.rewards.map(x=>x.message).join(' / '):'지급 보상 없음')]))}`}
function missions(d){return`<h3>현재 미션</h3>${table(['기간','미션','진행','보상'],d.missions.map(m=>[esc(({daily:'일일',weekly:'주간',monthly:'월간',run:'회차'})[m.period]),esc(m.description),m.progress+' / '+m.target+'<small>'+(m.claimed?'수령 완료':'미수령')+'</small>',esc(m.rewardLabel)]))}<div class="r27-stats">${stat('누적 출석',d.attendance.days+'일')}${stat('최근 기록의 연속 접속',d.attendance.streak+'일')}</div><p>연속 접속일수가 누적되면 보상이 있습니다. 최근 출석일: ${esc(d.attendance.lastDate||'기록 없음')}</p>${table(['출석일','주기 일수','연속 일수'],d.attendance.history.map(r=>[esc(r.date),r.cycleDay,r.streak]))}<p class="r27-note">현재 미션 진행은 선택한 과거 기간을 재현한 값이 아닙니다. 아래 지급 내역과 출석 이력만 조회 기간으로 필터링합니다.</p><h3>미션 수령 이력</h3>${table(['미션','수령 시각','실제 지급'],d.missionClaims.map(r=>[esc(r.missionId),date(r.at),esc(r.result.message)]))}`}
function collection(d){const c=d.collection;return`<div class="r27-stats">${stat('도감 등록',c.registered+' / '+c.slots)}${stat('일반 카드',c.normalCards+'장')}${stat('이로치 카드',c.shinyCards+'장')}${stat('사건·등급 완성',c.sets+' / 70')}</div><p>등급 전체 완성: ${esc(c.tiers.map(r=>({normal:'노말',rare:'레어',unique:'유니크',legend:'전설',myth:'신화'})[r]).join(' · ')||'아직 없음')}</p><h3>실제 보상 지급 내역</h3>${rewards(d.rewards)}<p class="r27-note">도감 보유량은 현재 값입니다. 지급 내역은 당시 서버 결과이며 서로 다른 보상 경로를 단순 합산하지 않습니다.</p>`}
function section(d,tab){if(tab==='learning')return learning(d);if(tab==='games')return games(d.games)+'<h3>최근 시도 (최대 100개)</h3>'+attempts(d.attempts);if(tab==='xp')return xp(d);if(tab==='missions')return missions(d);return collection(d)}
function boardPanel(p){const d=p.data;if('value'in d)return`<div class="r27-board-value">${p.key==='classMastery'?pct(d.value):esc(d.value)+(d.total===undefined?'':`<small> / ${d.total}명</small>`)}</div>`;
 const rows=d.rows||[];if(!rows.length)return'<p class="r27-empty">아직 표시할 기록이 없습니다.</p>';
 return`<div class="r27-board-list">${rows.map(r=>`<article><span>${esc(r.displayName||r.title||'')}${r.variant?'<small>'+esc(r.variant)+'</small>':''}</span><strong>${r.elapsedMs!==undefined?ms(r.elapsedMs):r.level!==undefined?'Lv. '+r.level:r.value!==undefined?esc(r.value):r.rate!==undefined?pct(r.rate):r.errorRate!==undefined?pct(r.errorRate):esc(({normal:'노말',rare:'레어',unique:'유니크',legend:'전설',myth:'신화'})[r.rarity]||'')}</strong>${r.displayName&&r.title?'<small>'+esc(r.title)+'</small>':''}</article>`).join('')}</div>`;
}
g.ReportUI27={esc,date,pct,ms,flag,table,stat,games,attempts,rewards,section,boardPanel};
})(window);
