/* Pure presentation. All counts, variants, completion claims and missions come from server responses. */
let filter25={type:'all',rarity:'all',event:'all'},replay25=null,fxContext25=null,owner25='';
const book25=()=>state42?.collection25;
const entry25=(eventId,rarity)=>book25()?.entries.find(x=>x.eventId===eventId&&x.rarity===rarity);
const variant25=(e,r,f)=>book25()?.variants.find(x=>x.eventId===e&&x.rarity===r&&x.effect===f);
const effectName25=f=>book25()?.effectNames[f]||'일반';
const acquired25=x=>!!(x?.normalSeen||x?.effects.length);
const normal25=(e,r)=>entry25(e,r)?.normalCount||0;
function fresh25(e,r){const rows=[...(state42?.cards||[]).filter(x=>x.legacyId===e&&x.rarity===r),...(book25()?.variants||[]).filter(x=>x.eventId===e&&x.rarity===r)];const day=state42?.periods.day;return rows.some(x=>x.firstAcquiredAt&&new Date(Date.parse(x.firstAcquiredAt)+9*3600000).toISOString().slice(0,10)===day)}
function effectMarkup25(html,fx){if(!fx||fx==='normal'||!/^\d\d$/.test(fx))return html;return html.replace('class="history-card ',`data-shiny-effect="${fx}" class="history-card shiny25 effect25-${fx} `).replace('<section class="history-card__face history-card__front" aria-hidden="false">','<section class="history-card__face history-card__front" aria-hidden="false"><div class="shiny25-overlay" aria-hidden="true"><i></i><i></i><i></i><i></i></div>')}
const markupBase25=collectionMarkup41;
function cardMarkup25(e,r,count,mode,fx){return effectMarkup25(markupBase25(e,r,count,mode),fx)}
collectionMarkup41=function(e,r,count,mode='list'){
 let fx=fxContext25;
 if(fx===null&&cardInspect?.event.id===e&&cardInspect?.rar.id===r)fx=cardInspect.effect||'normal';
 if(fx===null&&mode==='reveal'){const x=packReward?.cards[packReward.cursor];if(x?.event.id===e&&x.rar.id===r)fx=x.effect||'normal'}
 if(fx===null)fx=entry25(e,r)?.representative||'normal';return cardMarkup25(e,r,count,mode,fx);
};
collectionBookV34=function(){
 const b=book25();if(!b)return'<p>도감 설정을 불러오는 중입니다.</p>';
 const allEntries=b.entries,owned=allEntries.filter(acquired25).length,opts=(list,value)=>list.map(([v,n])=>`<option value="${v}" ${String(v)===String(value)?'selected':''}>${escape41(n)}</option>`).join('');
 return `<div class="book25"><h2>카드 도감 ${owned}/70</h2><p>한 칸 안에 일반 카드와 이로치를 함께 보관합니다. 완성은 보유 수량이 아닌 최초 획득 이력으로 판정합니다.</p><div class="filters25"><label>카드 보기<select onchange="filter25.type=this.value;render42()">${opts([['all','전체'],['normal','일반 획득'],['shiny','이로치 보유'],['missing','이로치 미보유'],['new','NEW']],filter25.type)}</select></label><label>등급<select onchange="filter25.rarity=this.value;render42()">${opts([['all','전체 등급'],...HistoryCards.TIERS.map(r=>[r.id,r.name])],filter25.rarity)}</select></label><label>사건<select onchange="filter25.event=this.value;render42()">${opts([['all','전체 사건'],...CH.map(e=>[e.id,e.title])],filter25.event)}</select></label></div><div class="badges25">${b.completions.filter(x=>x.kind==='tier').map(x=>`<button class="tierbadge25 ${x.rarity}" onclick="replayCompletion25('${x.completionId}')">${rarityById(x.rarity).name} 도감 완성</button>`).join('')}<span>이로치 조각 ${b.shards}개 · 교환 기능 준비 중</span></div>
 ${HistoryCards.TIERS.filter(r=>filter25.rarity==='all'||filter25.rarity===r.id).map(r=>`<section><h3>${r.name}</h3><div class="collectiongrid">${CH.filter(e=>filter25.event==='all'||+filter25.event===e.id).filter(e=>{const x=entry25(e.id,r.id),vs=b.variants.filter(v=>v.eventId===e.id&&v.rarity===r.id&&v.count>0);return filter25.type==='all'||filter25.type==='normal'&&x.normalSeen||filter25.type==='shiny'&&vs.length||filter25.type==='missing'&&!vs.length||filter25.type==='new'&&fresh25(e.id,r.id)}).map(e=>{const x=entry25(e.id,r.id),fx=x.representative||'normal',n=fx==='normal'?x.normalCount:variant25(e.id,r.id,fx)?.count||0,known=acquired25(x);return `<div class="entry25" data-collection-key="${e.id}:${r.id}"><button class="card-button25" onclick="inspect25(${e.id},'${r.id}')" aria-label="${escape41(e.title)} ${r.name} 상세">${known?cardMarkup25(e.id,r.id,n,'list',fx):`<div class="unowned25">${cardMarkup25(e.id,r.id,0,'list','normal')}<strong>미획득</strong></div>`}</button>${x.effects.length?`<span class="shinycorner25">✨ 이로치 ${x.effects.length}/${b.effects[r.id].length}</span>`:''}<div class="entrycaption25"><b>${escape41(e.title)}</b><span>${x.normalSeen?'일반 등록':'일반 미등록'} · 이로치 ${x.effects.length}/${b.effects[r.id].length}</span>${fresh25(e.id,r.id)?'<b class="new42">NEW</b>':''}${x.complete?'<span class="completed25">수집 완성 ✓</span>':''}</div></div>`}).join('')}</div></section>`).join('')}</div>`;
};
function inspect25(e,r,fx){const x=entry25(e,r);cardInspect={event:CH.find(x=>x.id===e),rar:rarityById(r),count:normal25(e,r),flipped:false,effect:fx||x?.representative||'normal',tab:fx&&fx!=='normal'?'shiny':'normal'};render42();document.querySelector('.inspectclose')?.focus()}
inspectCard=function(ev,e,r,n){ev?.stopPropagation?.();const x=packReward?.cards[packReward.cursor];inspect25(e,r,x?.event.id===e&&x?.rar.id===r?x.effect:undefined)};
function pickEffect25(f){cardInspect.effect=f;cardInspect.flipped=false;render42()}
function pref25(action){const c=cardInspect,p={action,eventId:c.event.id,rarity:c.rar.id,effect:c.effect};if(action==='lock')p.locked=!variant25(p.eventId,p.rarity,p.effect)?.locked;run42(async()=>{applyState42((await api42.request('collection.preference',p)).student);render42()})}
cardInspectModal=function(){if(!cardInspect)return'';const c=cardInspect,e=c.event.id,r=c.rar.id,p=entry25(e,r),fx=c.effect||'normal',v=variant25(e,r,fx),known=fx==='normal'?p?.normalSeen:p?.effects.includes(fx),n=fx==='normal'?normal25(e,r):v?.count||0;return`<div class="cardinspect v41-inspect" role="dialog" aria-modal="true" aria-label="카드 변형 상세" onclick="closeInspect41()"><div class="inspectpanel v41-inspect-panel inspect25" onclick="event.stopPropagation()"><button class="inspectclose" onclick="closeInspect41()" aria-label="닫기">×</button><h2>${escape41(c.event.title)} · ${c.rar.name}</h2><div class="tabs25"><button class="${fx==='normal'?'on':''}" onclick="pickEffect25('normal')">일반 ${normal25(e,r)}장</button><button class="${fx!=='normal'?'on':''}" onclick="pickEffect25('${book25().effects[r][0]}')">이로치 ${p.effects.length}/${book25().effects[r].length}</button></div>${fx!=='normal'?`<div class="effectbuttons25">${book25().effects[r].map(f=>`<button class="${fx===f?'on':''}" onclick="pickEffect25('${f}')">${p.effects.includes(f)?'✨':'🔒'} ${effectName25(f)} · ${variant25(e,r,f)?.count||0}장</button>`).join('')}</div>`:''}<div class="${known?'':'unowned25'}">${cardMarkup25(e,r,n,'detail',fx)}${known?'':'<strong>미획득 효과 미리보기</strong>'}</div><p>${escape41(effectName25(fx))} · 보유 ${n}장${fx!=='normal'?' · 중복 '+Math.max(0,n-1)+'장':''}</p><div class="actions25"><button class="btn" onclick="pref25('representative')" ${known?'':'disabled'}>대표 카드로 설정</button>${fx!=='normal'?`<button class="btn alt" onclick="pref25('lock')" ${n?'':'disabled'}>${v?.locked!==false?'🔒 잠금 해제':'잠금 설정'}</button>`:''}</div><p class="inspecttip">카드를 누르면 뒤집힙니다. 잠금을 풀어도 각 변형의 마지막 1장은 합성에 사용할 수 없습니다.</p></div></div>`};
const resultBase25=packResultCardV39;packResultCardV39=x=>{fxContext25=x.effect||'normal';try{return resultBase25(x).replace('</div>',`${x.shiny?`<span class="shinylabel25">✨ ${effectName25(x.effect)}</span>`:''}</div>`)}finally{fxContext25=null}};
const rewardBase25=rewardModal;rewardModal=()=>{let html=rewardBase25();const x=packReward?.cards[packReward.cursor];if(x?.shiny&&packReward.phase==='shown')html=html.replace('<p class="packprogress38">',`<p class="shiny-banner25">✨ 이로치 · ${effectName25(x.effect)}</p><p class="packprogress38">`);return html};
const fusionBase25=fusionPageV34;
fusionPageV34=()=>fusionBase25()+`<section class="shiny-fusion25"><h3>잠금 해제한 이로치 중복 카드</h3><p>자동 선택은 일반 카드만 사용합니다. 이로치는 직접 선택해야 하며 마지막 1장은 보존됩니다.</p>${(book25()?.variants||[]).filter(v=>v.locked===false&&v.count>1).map(v=>`<button class="btn alt" onclick="addShinyFusion25(${v.eventId},'${v.rarity}','${v.effect}')">${escape41(CH.find(e=>e.id===v.eventId).title)} · ${rarityById(v.rarity).name} · ${effectName25(v.effect)} (${v.count}장)</button>`).join('')||'<p>선택 가능한 이로치 중복 카드가 없습니다.</p>'}</section>`;
function addShinyFusion25(e,r,f){const v=variant25(e,r,f),used=fusionSlotsV34.filter(x=>x.eventId===e&&x.rarityId===r&&x.effect===f).length;if(fusionSlotsV34.length<5&&v?.locked===false&&v.count-used>1){fusionSlotsV34.push({eventId:e,rarityId:r,effect:f});render42()}}
performFusionV34=()=>{if(fusionSlotsV34.length!==5||!confirm('선택한 5장을 합성할까요? 선택한 이로치 중복도 재료로 소모됩니다.'))return;run42(async()=>{const out=await api42.request('cards.synthesize',{materials:fusionSlotsV34.map(x=>({eventId:x.eventId,rarity:x.rarityId,effect:x.effect||'normal'}))});applyState42(out.student);fusionSlotsV34=[];packReward={source:'합성 결과',packType:out.card.rarity,cards:[cardFrom42(out.card)],cursor:0,phase:'shown',revealed:1,lastReveal:0};render42()})};
missions42=function(){return`<section class="shell"><h2>교사 선택 미션</h2>${(state42?.missions||[]).map((m,i)=>`<div class="v42-mission"><span><b>${escape41(m.title)}</b><small>${escape41(m.description||'')}<br>${m.progress}/${m.target} · ${escape41(m.rewardLabel||packByIdV36(m.reward).name+' '+m.rewardCount+'개')}</small></span><button class="btn alt" onclick="claimIndex25(${i})" ${m.claimed||m.progress<m.target?'disabled':''}>${m.claimed?'수령 완료':'보상 받기'}</button></div>`).join('')||'<p>진행 중인 미션이 없습니다.</p>'}<h3>현재 출석 보상</h3>${(state42?.attendanceLabels||[]).map(s=>`<p>${escape41(s)}</p>`).join('')}</section>`};
function claimIndex25(i){const m=state42.missions[i];run42(async()=>{const out=await api42.request('missions.claim',{missionId:m.id,runId:m.runId});applyState42(out.student);if(out.result)toast42(out.result.message);render42()})}
function activeCelebration25(){if(!state42||state42.testOnly||packReward||openPlan42||cardInspect||stage2Overlay())return null;return replay25||book25()?.completions.find(x=>!x.seenAt)}
function replayCompletion25(k){replay25=book25().completions.find(x=>x.completionId===k)||null;render42()}
function celebration25(x){const tier=rarityById(x.rarity),e=CH.find(e=>e.id===x.eventId),cards=x.kind==='set'?['normal',...book25().effects[x.rarity]].map(f=>({e:x.eventId,f})):CH.slice(0,4).map(e=>({e:e.id,f:entry25(e.id,x.rarity)?.representative||'normal'}));return`<div class="celebration25 ${x.rarity}" role="dialog" aria-modal="true" aria-labelledby="celebration-title25"><section><p class="celebration-kicker25">COLLECTION COMPLETE</p><h2 id="celebration-title25">축하합니다!</h2><p class="celebration-message25 ${x.kind==='tier'?'tier-message25':''}">${tier.name} ${x.kind==='set'?`‘${escape41(e.title)}’ 카드 수집을`:'카드 도감을'} 완성하였습니다!</p>${x.kind==='tier'?`<div class="tierbadge25 badge-large25 ${x.rarity}">${tier.name} 도감 완성 휘장</div>`:''}<div class="celebration-cards25 ${x.kind==='tier'?'tier-sequence25':''}">${cards.map((v,i)=>`<div style="--card-index:${i}">${cardMarkup25(v.e,x.rarity,v.f==='normal'?normal25(v.e,x.rarity):variant25(v.e,x.rarity,v.f)?.count||0,'list',v.f)}<b>${escape41(effectName25(v.f))}</b></div>`).join('')}</div>${x.kind==='tier'?'<p>14사건의 일반 카드와 모든 이로치를 수집했습니다.</p>':''}<p class="completion-reward25">${escape41(x.result?.message||'완성 기록을 저장했습니다.')}</p><div class="actions25"><button class="btn" onclick="finishCelebration25('view')">완성한 카드 보기</button><button class="btn alt" onclick="finishCelebration25('book')">카드 도감으로</button><button class="btn alt" onclick="finishCelebration25('continue')">계속하기</button></div></section></div>`}
function finishCelebration25(action){const x=activeCelebration25();if(!x)return;run42(async()=>{if(!x.seenAt){await api42.request('collection.ack',{ids:[x.completionId]});await refresh42()}replay25=null;if(action==='view'&&x.kind==='set'){inspect25(x.eventId,x.rarity);return}if(action!=='continue'){view='collection';collectionModeV34='book';filter25={type:'all',rarity:x.rarity,event:'all'}}render42()})}
const renderBase25=render42;render42=function(){const owner=state42?.profile.id||'';if(owner25!==owner){owner25=owner;replay25=null;filter25={type:'all',rarity:'all',event:'all'}}renderBase25();const x=activeCelebration25();if(x){app.insertAdjacentHTML('beforeend',celebration25(x));document.querySelector('.celebration25 .btn')?.focus({preventScroll:true})}};
render=renderV28=renderV29=renderV30=renderV31=renderV32=renderV33=renderV34=renderV35=renderV36=renderV37=renderV38=renderV39=renderV40=renderV41=render42;
addEventListener('keydown',e=>{const panel=document.querySelector('.celebration25');if(!panel)return;if(e.key==='Escape'){e.preventDefault();finishCelebration25('continue')}if(e.key==='Tab'){const bs=panel.querySelectorAll('button'),first=bs[0],last=bs[bs.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}});
// Preserve runtime-loaded legacy style ordering; new effects are scoped to .shiny25 only.
const style25=document.querySelector('link[href="stage25.css"]');if(style25)document.head.appendChild(style25);
