/* Private record view: no other student IDs can be requested. */
let records27=null,recordTab27='learning',recordPeriod27='all',recordsLoading27=false,recordsOwner27='',recordRequest27=0;
const recordTabs27={learning:'학습 현황',games:'게임 기록',xp:'XP·레벨',missions:'미션·출석',collection:'카드 수집'};
const gate26For27=gate42;gate42=v=>v==='records27'?!!state42:gate26For27(v);
async function loadRecords27(){if(recordsLoading27)return;const owner=state42?.profile.id;recordsOwner27=owner;const seq=++recordRequest27;recordsLoading27=true;try{const result=await api42.request('student.records.read',{period:recordPeriod27});if(seq===recordRequest27&&state42?.profile.id===owner)records27=result}catch(e){toast42(e.message)}finally{recordsLoading27=false;if(view==='records27')render42()}}
function recordsPage27(){const E=ReportUI27.esc;if(recordsOwner27!==state42?.profile.id){recordsOwner27=state42?.profile.id;records27=null;recordTab27='learning';recordRequest27++}
 if(!records27)return`<section class="shell r27"><h2>나의 학습 기록</h2><p>서버가 확인한 나의 기록만 조회합니다.</p><button class="btn" onclick="loadRecords27()" ${recordsLoading27?'disabled':''}>${recordsLoading27?'불러오는 중…':'기록 불러오기'}</button></section>`;
 if(records27.testOnly)return`<section class="shell r27"><h2>교사 연습모드</h2><p>${E(records27.message)}</p></section>`;
 return`<section class="shell r27"><div class="r27-heading"><div><p class="eyebrow">MY LEARNING ARCHIVE</p><h2>나의 학습 기록</h2></div><button class="btn alt" onclick="loadRecords27()">새로고침</button></div><div class="r27-tabs">${Object.entries(recordTabs27).map(([k,v])=>`<button class="${recordTab27===k?'on':''}" onclick="recordTab27='${k}';render42()">${v}</button>`).join('')}</div><label>이력 조회 기간<select onchange="recordPeriod27=this.value;loadRecords27()">${Object.entries({all:'전체 기간',today:'오늘',last7:'최근 7일',weekly:'이번 주 월~금',monthly:'이번 달'}).map(([k,v])=>`<option value="${k}" ${recordPeriod27===k?'selected':''}>${v}</option>`).join('')}</select></label><p class="r27-note">누적 숙련·보유량·레벨은 현재 값, 오늘 학습은 한국시간 오늘 기준입니다. 최근 이력만 선택 기간을 적용합니다.</p>${ReportUI27.section(records27,recordTab27)}<details><summary>집계 기준과 과거 기록 안내</summary>${Object.values(records27.formulas).map(t=>`<p>${E(t)}</p>`).join('')}</details></section>`;
}
const go26For27=go;go=function(v){go26For27(v);if(v==='records27'&&view==='records27')loadRecords27()};
const render26For27=render42;render42=function(){if(!state42){records27=null;recordsOwner27='';recordRequest27++}render26For27();const s=document.querySelector('link[href="stage27.css"]');if(s)document.head.appendChild(s)};
const rank26For27=rankMarkup42;let rankKey27='';
loadRank42=async function(mode='speedrun',rewardKey=''){view='rankings';rank42=null;rankKey27=rewardKey||(mode==='connections'?'connections.basic':mode==='revolutionmap'?'revolutionmap.memory':'');render42();await run42(async()=>{rank42=await api42.request('rankings.read',{mode,rewardKey:rankKey27});render42()})};
rankMarkup42=function(){let h=rank26For27();if(!rank42)return h;const keys=Object.values(state42.rewardPreviews||{}).filter(r=>r.mode===rank42.mode);if(['connections','revolutionmap'].includes(rank42.mode))h=h.replace('<div class="rank42">',`<label>게임 조건<select onchange="loadRank42('${rank42.mode}',this.value)">${keys.map(r=>`<option value="${r.key}" ${rankKey27===r.key?'selected':''}>${ReportUI27.esc(r.label)}</option>`).join('')}</select></label><div class="rank42">`);return h.replaceAll("'—'","'기록 없음'")+`<p class="r27-note">미끼런은 8장, 짝맞추기는 고급 12세트의 공식 기록만 순위에 표시합니다. 모든 세부 조건의 정상 완료 이력은 ‘나의 기록’에서 확인하세요.</p>`};
render=renderV28=renderV29=renderV30=renderV31=renderV32=renderV33=renderV34=renderV35=renderV36=renderV37=renderV38=renderV39=renderV40=renderV41=render42;
