/* Teacher archive and display configuration. Nothing is written by merely opening a view. */
let reportData27=null,reportDetail27=null,reportSettings27=null,reportFilter27={period:'today'},errorUnit27='events',teacherRecordTab27='learning',reportPending27=false,reportOwner27='',reportAutoOwner27='',reportSequence27=0;
const U27=ReportUI27,periods27={today:'오늘',last7:'최근 7일',weekly:'이번 주 월~금',monthly:'이번 달',all:'전체 기간',custom:'날짜 직접 지정'};
const exportKinds27={students:'학생 요약',mastery:'60문항 숙련',attempts:'게임별 시도',errors:'오답 통계',xp:'XP·레벨',missions:'미션·출석',rewards:'보상 지급',review:'검토·보안'};
function reportFilters27(){const p=reportFilter27;return`<form onsubmit="queryReport27(event)"><div class="formgrid"><label>학년도<input name="schoolYear" type="number" value="${p.schoolYear||year}" required></label><label>학년 (전체는 빈칸)<input name="grade" type="number" min="1" max="6" value="${p.grade||''}"></label><label>반 (학년과 함께)<input name="classNo" type="number" min="1" max="99" value="${p.classNo||''}"></label><label>학생<select name="studentId">${opts({'':'전체',...Object.fromEntries(info.students.map(s=>[s.id,s.grade+'학년 '+s.classNo+'반 '+s.number+'번 '+s.name]))},p.studentId||'')}</select></label><label>기간<select name="period">${opts(periods27,p.period)}</select></label><label>시작일<input name="from" type="date" value="${E(p.from||'')}"></label><label>종료일<input name="to" type="date" value="${E(p.to||'')}"></label></div><button class="primary" ${reportPending27?'disabled':''}>${reportPending27?'조회 중…':'서버 기록 조회'}</button></form><p class="r27-note">로그인한 학년도와 허용된 반만 조회합니다. 다른 학년도는 해당 학년도로 로그인하세요. 누적 숙련·레벨은 현재 값, 기본 복습·완전 숙련은 오늘 값입니다.</p>`}
async function fetchReport27(){if(reportPending27)return;reportPending27=true;const owner=API.session?.token,seq=++reportSequence27;try{const p={schoolYear:year,...reportFilter27,legacy:tab==='legacy27'};const result=await API.request('teacher.records.read',p);if(owner!==API.session?.token||seq!==reportSequence27)return;reportData27=result;reportDetail27=null;render()}catch(e){msg(e.message)}finally{reportPending27=false;render()}}
function queryReport27(e){e.preventDefault();const p=Object.fromEntries(new FormData(e.target));p.schoolYear=+p.schoolYear;for(const k of ['grade','classNo']){if(p[k])p[k]=+p[k];else delete p[k]}if(!p.studentId)delete p.studentId;reportFilter27=p;fetchReport27()}
function teacherStats27(d){return`<div class="r27-stats">${U27.stat('등록 학생',d.summary.students+'명')}${U27.stat('기간 로그인 (2.7 이후 이력)',d.summary.loggedIn+'명')}${U27.stat('기간 참여',d.summary.participated+'명')}${U27.stat('오늘 기본 복습',d.summary.basic+'명')}${U27.stat('오늘 완전 숙련',d.summary.fullToday+'명')}${U27.stat('현재 누적 숙련률',U27.pct(d.summary.masteryRate))}</div>`}
function errorTable27(d){const rows=d.errors[errorUnit27];return`<label>오답 분석 단위<select onchange="errorUnit27=this.value;render()">${opts({events:'사건별',types:'유형별',questions:'개별 문항'},errorUnit27)}</select></label>${U27.table(['항목','응답 / 오답','정답률','전체 응답 오답률','학생×문항 첫 응답 / 첫 오답','첫 시도 오답 비율'],rows.map(r=>[E(r.label),r.responses+' / '+r.wrong,U27.pct(r.errorRate===null?null:1-r.errorRate),U27.pct(r.errorRate),r.firstStudentQuestions+' / '+r.firstWrong,U27.pct(r.firstErrorRate)]))}<p>${E(d.errors.formula)}</p><p class="r27-note">상세 응답 없는 과거 정상 시도 ${d.errors.coverage.legacyAttempts}개는 오답률 계산에서 제외했습니다.</p>`}
function teacherRecordsPage27(){const d=reportData27;return`<section class="panel r27"><h2>${tab==='legacy27'?'이전 버전 기록':'학습 기록·통계'}</h2>${reportFilters27()}${d?`<h3>${E(d.period.label)} · 한국시간 기준</h3>${tab==='legacy27'?'<p>도전·페이스오프는 조회만 가능합니다. 새 기록·보상·순위 등록은 비활성입니다.</p>'+U27.attempts(d.legacy):teacherStats27(d)+`<h3>학생별 현황</h3>${U27.table(['학생','숙련도','초급 / 중급','오늘 학습','기본 복습','레벨 / 기간 XP','상세'],d.students.map(s=>[E(s.grade+'학년 '+s.classNo+'반 '+s.number+'번 '+s.name),s.mastered+'/60'+(s.masteryUnknown?' · 일부 집계 불가':''),s.beginner+'/24 · '+s.intermediate+'/36',s.studiedToday?'참여':'미참여',s.basic.complete?'완료':'미완료','Lv. '+s.level+' / '+s.periodXP+' XP',`<button onclick="openStudentReport27('${s.studentId}')">개인 기록</button>`]))}<p>오늘 학습하지 않은 학생: ${E(d.students.filter(s=>!s.studiedToday).map(s=>s.number+'번 '+s.name).join(', ')||'없음')}</p><details open><summary>게임별 기록·중단·포기</summary>${U27.games(d.games)}<p>시도 ${d.attemptTotal}개 중 최근 최대 100개 표시. 전체 이력은 범위를 나누어 CSV로 확인하세요.</p>${U27.attempts(d.attempts)}</details><details><summary>정답·오답 분석</summary>${errorTable27(d)}</details><details><summary>실제 보상 지급 내역</summary>${U27.table(['학생','종류','시각','지급 내용'],d.rewards.map(r=>[E(d.students.find(s=>s.studentId===r.studentId)?.name||'학생'),E(r.kind),U27.date(r.at),E(r.message)]))}</details><details><summary>검토·보안 거부</summary>${U27.attempts(d.attempts.filter(r=>['review','too_short','excluded'].includes(r.classification)))}${U27.table(['시각','대상','요청 종류','안내 코드'],d.security.map(r=>[U27.date(r.at),E(d.students.find(s=>s.studentId===r.studentId)?.name||'교사 본인'),E(r.action),E(r.code)]))}<p>교사 본인과 조회 대상 학생의 인증 세션으로 확인되는 거부만 표시합니다. 익명·만료 세션 등 대상 연결이 불가능한 거부는 집계 불가이며 원본 보안 이력에 보존됩니다.</p></details><details><summary>교사 연습 (학생 통계 제외)</summary>${U27.table(['게임','시각','상태'],d.teacherPractice.map(r=>[E(modeNames[r.mode]||r.mode),U27.date(r.at),E(r.status)]))}</details><details><summary>통계 계산 기준</summary>${Object.values(d.formulas).map(t=>`<p>${E(t)}</p>`).join('')}</details>`}`:'<p>조건을 선택하고 조회하세요.</p>'}</section>${reportDetail27?teacherStudentDetail27():''}<section class="panel r27"><h2>현재 조회 조건으로 CSV 내보내기</h2><p>조회 버튼으로 적용한 학년도·반·학생·기간을 사용합니다. UTF-8 BOM, 최대 10,000행. 숙련·레벨·현재 미션은 현재 값임을 구분합니다.</p><label>종류<select id="exportKind27">${opts(exportKinds27,'students')}</select></label><button onclick="exportReport27()">권한 확인 후 다운로드</button></section>`}
async function openStudentReport27(studentId){await task(async()=>{const owner=API.session?.token,result=await API.request('teacher.records.student',{schoolYear:year,...reportFilter27,studentId});if(owner!==API.session?.token)return;reportDetail27=result;teacherRecordTab27='learning';render();document.querySelector('#studentDetail27')?.scrollIntoView({behavior:'smooth',block:'start'})})}
function teacherStudentDetail27(){const d=reportDetail27;return`<section id="studentDetail27" class="panel r27"><h2>${E(d.summary.name)} · 개인 기록</h2><div class="r27-tabs">${Object.entries({learning:'학습 현황',games:'게임 기록',xp:'XP·레벨',missions:'미션·출석',collection:'카드 수집'}).map(([k,n])=>`<button class="${teacherRecordTab27===k?'on':''}" onclick="teacherRecordTab27='${k}';render()">${n}</button>`).join('')}</div>${U27.section(d,teacherRecordTab27)}</section>`}
function exportReport27(){const kind=document.querySelector('#exportKind27').value;task(async()=>{const r=await API.request('teacher.records.csv',{schoolYear:year,...reportFilter27,legacy:tab==='legacy27',kind});const url=URL.createObjectURL(new Blob([r.content],{type:r.mime})),a=document.createElement('a');a.href=url;a.download=r.filename;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);msg(r.rows+'행을 내려받았습니다.')})}
function reportSettingsPage27(){const r=reportSettings27;if(!r)return`<section class="panel r27"><h2>기록·전광판 설정</h2><button onclick="loadReportSettings27()">설정 불러오기</button></section>`;const s=r.settings;return`<section class="panel r27"><h2>기록·전광판 설정</h2><p>전광판은 별도 창에서 전광판 API만 읽습니다. 기본 학생 이름은 일부 가림입니다.</p><form onsubmit="saveReportSettings27(event)"><h3>표시 항목</h3><div class="r27-checks">${Object.entries(r.panels).map(([k,n])=>`<label><input type="checkbox" name="panel_${k}" ${s.panels[k]?'checked':''}>${E(n)}</label>`).join('')}</div><div class="formgrid"><label>학생 이름 표시<select name="nameMode">${opts({name:'실명',surname:'성만 표시',masked:'이름 일부 가림',number:'학생 번호',alias:'익명 별칭',none:'개인 관련 항목 표시 안 함'},s.nameMode)}</select></label><label>화면 전환<select name="rotateSeconds">${opts({0:'자동 전환 없음',5:'5초',10:'10초',15:'15초',30:'30초'},s.rotateSeconds)}</select></label><label>서버 새로고침 (15~300초)<input name="refreshSeconds" type="number" min="15" max="300" value="${s.refreshSeconds}"></label><label>오늘의 성장<select name="growth">${opts({new_mastery:'오늘 처음 숙련 확정한 문항 수',today_success:'오늘 성공한 서로 다른 문항 수',xp:'오늘 정상 학습 XP'},s.growth)}</select></label><label><input type="checkbox" name="legacyVisible" ${s.legacyVisible?'checked':''}>교사 이전 버전 기록 표시</label><label><input type="checkbox" name="csvEnabled" ${s.csvEnabled?'checked':''}>인증 교사 CSV 내보내기 허용</label></div><h3>전광판 게임</h3><div class="r27-checks">${Object.entries(r.games).map(([k,n])=>`<label><input type="checkbox" name="game_${k}" ${s.games.includes(k)?'checked':''}>${E(n)}</label>`).join('')}</div><label>원본 기록 보존 안내<textarea name="retentionNotice" maxlength="500">${E(s.retentionNotice)}</textarea></label><p>진행 중 게임 보관 설정: ${E(r.retention)}. 원본 기록 자동 삭제는 이번 단계에서 실행하지 않습니다.</p><button class="primary">설정 저장</button></form><div class="actions"><a class="r27-link" href="board.html" target="_blank" rel="noopener">전광판 새 창 열기</a></div><p>새 창에서 교사 인증이 필요할 수 있습니다. 전체 화면과 반 선택은 전광판에서 설정합니다.</p></section>`}
async function loadReportSettings27(){await task(async()=>{const owner=API.session?.token,result=await API.request('teacher.records.settings',{schoolYear:year});if(owner!==API.session?.token)return;reportSettings27=result;render()})}
function saveReportSettings27(e){e.preventDefault();const f=e.target.elements,old=reportSettings27.settings,value={...old,panels:Object.fromEntries(Object.keys(reportSettings27.panels).map(k=>[k,f['panel_'+k].checked])),games:Object.keys(reportSettings27.games).filter(k=>f['game_'+k].checked),nameMode:f.nameMode.value,rotateSeconds:+f.rotateSeconds.value,refreshSeconds:+f.refreshSeconds.value,growth:f.growth.value,legacyVisible:f.legacyVisible.checked,csvEnabled:f.csvEnabled.checked,retentionNotice:f.retentionNotice.value};task(async()=>{const out=await API.request('teacher.records.settings.save',{schoolYear:year,value});reportSettings27.settings=out.saved;render();msg('기록·전광판 설정을 저장했습니다.')})}
const overview26For27=overview;overview=function(){return`<section class="panel r27"><h2>프랑스 혁명 학습 대시보드</h2>${reportData27?'<p>'+E(reportData27.period.label)+' · 현재 적용한 조회 범위</p>'+teacherStats27(reportData27):'<p>학생 기록을 조회하면 오늘의 참여·복습·숙련 현황이 표시됩니다.</p>'}<div class="actions"><button onclick="setTab('records27')">기록·통계 열기</button><button onclick="setTab('display27')">전광판 설정</button><a class="r27-link" href="board.html" target="_blank" rel="noopener">전광판 열기</a></div></section>`+overview26For27()};
const setTab26For27=setTab;setTab=function(t){setTab26For27(t);if(['records27','legacy27'].includes(t))fetchReport27();if(t==='display27')loadReportSettings27()};
// Legacy modes are not silently offered in current rankings.
ranking=function(){return rankingBase26().replace('<label>기간<select',`<label>세부 조건 (연결고리·지도)<select name="rewardKey">${opts({'':'게임별 기본 조건','connections.basic':'연결고리 기본','connections.advanced':'연결고리 심화','revolutionmap.basic':'혁명 지도 기본','revolutionmap.memory':'혁명 지도 기억도전'},'')}</select></label><label>기간<select`)};
const renderTeacher26For27=render;render=function(){const owner=API.session?.token||'';if(reportOwner27!==owner){reportOwner27=owner;reportData27=null;reportDetail27=null;reportSettings27=null;reportFilter27={period:'today'};reportPending27=false;reportAutoOwner27='';reportSequence27++}renderTeacher26For27()};
const logoutTeacher26For27=logout;logout=async function(){reportData27=reportDetail27=reportSettings27=null;reportSequence27++;reportOwner27='';await logoutTeacher26For27()};
