/* Stage 2.6 teacher configuration. Changes are drafts until explicit server save. */
delete modeNames.challenge;delete modeNames.faceoff;Object.assign(modeNames,{connections:'혁명의 연결고리',revolutionmap:'사라진 혁명 지도'});
let draft26=null,stamp26='',levelEdit26=0;
function targets26(){return{'*':'전체 게임',...modeNames,'matching.basic':'짝맞추기 기본 전체','matching.advanced':'짝맞추기 고급 전체',...Object.fromEntries(info.completionCatalog.map(x=>[x.key,x.label])),...Object.fromEntries(info.learning26.bank.flatMap(e=>[['connections:'+e.id,'연결고리 · '+e.title],['revolutionmap:'+e.id,'혁명 지도 · '+e.title],...e.questions.map(q=>[q.id,(q.mode==='beginner'?'초급':'중급')+' '+q.type+'유형 · '+e.title])])),...Object.fromEntries(info.learning26.zones.map(z=>['zone:'+z.id,'지도 구성 · '+z.title]))}}
function lockFields26(l,i){return`<div class="lock-editor26"><div class="formgrid"><label>대상<select name="lock${i}_target">${opts(targets26(),l.target)}</select></label><label>적용 범위<select name="lock${i}_scope">${opts({year:'학년도 전체',class:'특정 반',student:'특정 학생'},l.scope)}</select></label><label>상태<select name="lock${i}_locked">${opts({true:'잠금',false:'이 범위에서 해제'},l.locked)}</select></label><label>학생<select name="lock${i}_student">${opts(Object.fromEntries(info.students.map(s=>[s.id,s.grade+'학년 '+s.classNo+'반 '+s.number+'번 '+s.name])),l.studentId)}</select></label><label>학년<input type="number" name="lock${i}_grade" value="${l.grade||2}" min="1" max="6"></label><label>반<input type="number" name="lock${i}_class" value="${l.classNo||1}" min="1" max="99"></label><label>잠금 표시<select name="lock${i}_display">${opts({show:'보이되 잠금 안내',hide:'학생 메뉴에서 숨김'},l.display)}</select></label><label class="wide">안내 문구<input name="lock${i}_message" maxlength="300" value="${E(l.message||'현재 교사가 점검 중인 게임입니다. 다른 학습 게임을 이용해 주세요.')}"></label></div><button type="button" onclick="removeLock26(${i})">이 규칙 제거</button></div>`}
function learningSettingsPage26(){const x=info.learning26,stamp=JSON.stringify(x.settings);if(stamp26!==stamp){draft26=copy(x.settings);stamp26=stamp;levelEdit26=0}const s=draft26,r=s.levelRewards[levelEdit26],fields={first:'최초 XP',repeat:'반복 XP',best:'최고기록 보너스',perfect:'완벽 보너스',noHint:'무힌트 보너스',dailyCount:'일일 횟수',reduceAfter:'감소 시작 횟수',percent:'감소 후 비율 %'};
 return`<section class="panel"><h2>학습·게임 잠금 및 레벨</h2><p>모든 변경은 아래 저장 버튼을 눌러야 적용됩니다. 과거 기록·카드·XP 지급 원장은 삭제하지 않습니다. 교사 연습모드는 모든 잠금을 우회해 시험할 수 있지만 보상은 없습니다.</p><form id="learningForm26" onsubmit="saveLearning26(event)"><details class="settings-section26" open><summary>게임·모드·개별 문항 잠금</summary><p>같은 대상은 학생 설정 → 반 설정 → 전체 설정 순서로 우선합니다. 상위 게임이나 전체 게임 잠금도 별도로 검사합니다. 필수 12사건 중 한 사건의 사용 가능한 유형이 없으면 학습을 시작하지 않습니다.</p>${s.locks.map(lockFields26).join('')}<button type="button" onclick="addLock26()">잠금 규칙 추가</button></details>
 <details class="settings-section26" open><summary>자동 판정·확인 판정 및 지도 힌트</summary><div class="formgrid">${['speedrun','baitrun'].map(m=>`<label>${modeNames[m]}<select name="submit_${m}">${opts({student:'학생 선택에 따름',auto:'배치 완료 시 자동 판정',confirm:'확인 눌러야 완료 판정'},s.submission[m])}</select></label>`).join('')}<label><input type="checkbox" name="mapOfficial" ${s.mapHints.official?'checked':''}>지도 힌트 사용 시 공식 기록 허용</label><label><input type="checkbox" name="mapBonus" ${s.mapHints.bonus?'checked':''}>지도 힌트 사용 시 보너스 XP 허용</label></div><p>재개된 지도·스피드런·미끼런은 연습 기록으로 처리합니다. 최고기록 여부와 완료 시각은 서버가 판정합니다.</p></details>
 <details class="settings-section26"><summary>게임·단계별 경험치</summary><div class="formgrid"><label>학생별 하루 XP 상한<input name="dailyCap" type="number" min="0" max="100000" value="${s.xp.dailyCap}"></label><label>최고 레벨<input name="maxLevel" type="number" min="2" max="500" value="${s.xp.maxLevel}"></label></div><label>레벨별 필요 누적 XP (Lv.1부터 쉼표로 구분, 첫 값은 0)<textarea class="thresholds26" name="thresholds">${s.xp.thresholds.join(', ')}</textarea></label><button type="button" onclick="generateThresholds26()">같은 간격으로 표 만들기</button><div class="tablewrap"><table class="teacher-xp26"><thead><tr><th>게임·단계</th><th>반복 정책</th>${Object.values(fields).map(n=>`<th>${n}</th>`).join('')}</tr></thead><tbody>${info.completionCatalog.map((c,i)=>{const r=s.xp.rules[c.key];return`<tr><th>${E(c.label)}</th><td><select name="xp${i}_policy">${opts({same:'항상 동일 반복 XP',decrease:'횟수 이후 감소',first:'최초만',none:'XP 없음'},r.policy)}</select></td>${Object.keys(fields).map(k=>`<td><input aria-label="${E(c.label+' '+fields[k])}" name="xp${i}_${k}" type="number" min="0" value="${r[k]}"></td>`).join('')}</tr>`}).join('')}</tbody></table></div></details>
 <details class="settings-section26"><summary>레벨 달성 카드·팩 보상</summary><p>각 규칙 ID·달성 레벨별 최초 1회 지급합니다. 설정 변경만으로 과거 레벨 보상은 지급되지 않습니다. 겹치는 규칙은 각각 지급되므로 확인하세요.</p>${s.levelRewards.length?`<label>편집할 규칙<select onchange="switchLevel26(this.value)">${opts(Object.fromEntries(s.levelRewards.map((r,i)=>[i,(i+1)+'. '+r.id])),levelEdit26)}</select></label><div class="formgrid"><label>고정 규칙 ID<input name="levelId" value="${E(r.id)}" readonly></label><label>지급 방식<select name="levelType">${opts({exact:'특정 레벨',every:'매 N레벨',range:'범위 안 각 레벨',max:'최고 레벨'},r.type)}</select></label><label>특정 레벨<input name="levelExact" type="number" min="1" max="500" value="${r.level}"></label><label>N레벨마다<input name="levelEvery" type="number" min="1" max="500" value="${r.every}"></label><label>범위 시작<input name="levelFrom" type="number" min="1" max="500" value="${r.from}"></label><label>범위 끝<input name="levelTo" type="number" min="1" max="500" value="${r.to}"></label></div>${rewardFields25('level_',r.reward)}<button type="button" onclick="removeLevel26()">이 규칙 제거</button>`:'<p>설정된 레벨 보상이 없습니다.</p>'}<button type="button" onclick="addLevel26()">레벨 보상 규칙 추가</button></details>
 ${[['basic','오늘의 기본 복습 — 초급 1회 + 중급 1회'],['daily','오늘의 완전 숙련 — 12사건 × 5유형']].map(([k,n])=>`<details class="settings-section26"><summary>${n}</summary><label><input type="checkbox" name="study_${k}" ${s.study[k].enabled?'checked':''}>하루 최초 1회 보상 사용</label>${rewardFields25('study_'+k+'_',s.study[k].reward)}</details>`).join('')}<button class="primary">학습·잠금·경험치·레벨 보상 전체 저장</button></form></section><section class="panel"><h2>12사건 × 5유형 문제 검토</h2><p>기존 정답 허용 목록은 보존합니다. 아래 문항 ID를 잠금 규칙에서 선택할 수 있습니다. 새 역사 설명은 실제 수업 교재와 대조해 주세요.</p>${x.bank.map(e=>`<details><summary>${e.id} ${E(e.title)}</summary><p>원인: ${E(e.cause)}<br>결과: ${E(e.effect)}</p>${e.questions.map(q=>`<p><b>${q.id} · ${q.mode==='beginner'?'초급':'중급'}</b><br>${E(q.prompts[0])}<br>허용: ${q.answers.map(E).join(' / ')}</p>`).join('')}</details>`).join('')}</section>`;
}
function captureLearning26(){const f=document.querySelector('#learningForm26');if(!f)return;const v=k=>f.elements[k].value,s=draft26;s.locks=s.locks.map((l,i)=>({...l,target:v('lock'+i+'_target'),scope:v('lock'+i+'_scope'),locked:v('lock'+i+'_locked')==='true',studentId:v('lock'+i+'_student'),grade:+v('lock'+i+'_grade'),classNo:+v('lock'+i+'_class'),display:v('lock'+i+'_display'),message:v('lock'+i+'_message')}));for(const m of ['speedrun','baitrun'])s.submission[m]=v('submit_'+m);s.mapHints={official:f.elements.mapOfficial.checked,bonus:f.elements.mapBonus.checked};s.xp.dailyCap=+v('dailyCap');s.xp.maxLevel=+v('maxLevel');s.xp.thresholds=v('thresholds').split(',').map(x=>Number(x.trim()));info.completionCatalog.forEach((c,i)=>{const r=s.xp.rules[c.key];for(const k of ['first','repeat','best','perfect','noHint','dailyCount','reduceAfter','percent'])r[k]=+v('xp'+i+'_'+k);r.policy=v('xp'+i+'_policy')});if(s.levelRewards.length)Object.assign(s.levelRewards[levelEdit26],{type:v('levelType'),level:+v('levelExact'),every:+v('levelEvery'),from:+v('levelFrom'),to:+v('levelTo'),reward:readReward25(f,'level_')});for(const k of ['daily','basic'])s.study[k]={enabled:f.elements['study_'+k].checked,reward:readReward25(f,'study_'+k+'_')};}
function addLock26(){captureLearning26();draft26.locks.push({target:'connections',scope:'year',locked:true,display:'show',grade:2,classNo:1,studentId:info.students[0]?.id||'',message:'현재 교사가 점검 중인 게임입니다. 다른 학습 게임을 이용해 주세요.'});render()}
function removeLock26(i){captureLearning26();draft26.locks.splice(i,1);render()}
function switchLevel26(i){captureLearning26();levelEdit26=+i;render()}
function addLevel26(){captureLearning26();draft26.levelRewards.push({id:'level-'+crypto.randomUUID(),type:'every',level:10,every:10,from:2,to:10,reward:{card:null,pack:null}});levelEdit26=draft26.levelRewards.length-1;render()}
function removeLevel26(){captureLearning26();draft26.levelRewards.splice(levelEdit26,1);levelEdit26=0;render()}
function generateThresholds26(){captureLearning26();const n=Number(prompt('레벨마다 필요한 XP 간격',100));if(!Number.isInteger(n)||n<=0)return;draft26.xp.thresholds=Array.from({length:Math.min(500,Math.max(2,draft26.xp.maxLevel))},(_,i)=>i*n);render()}
function saveLearning26(e){e.preventDefault();captureLearning26();task(async()=>{await API.request('teacher.learning.save',{schoolYear:year,value:draft26});await refresh();msg('학습·잠금·레벨 설정을 저장했습니다.')})}
const missionPageBase26=missionSettings25;missionSettings25=function(){return`<section class="panel"><h2>일일·주간·월간 미션</h2><p>일일 3개·주간 3개·월간 3개 기본안을 불러오거나 최대 40개까지 추가할 수 있습니다. 기존 초안은 확인 후에만 교체되며 현재 실행 중인 회차는 그대로 유지됩니다.</p><button onclick="presetMissions26()">9개 기본안 불러오기</button></section>`+missionPageBase26()+`<section class="panel"><h2>학생·반별 미션 관리</h2><p>진행도 초기화는 이미 받은 보상을 다시 주지 않습니다. 추가 회차는 새 미션 실행 ID를 만들며 보상 재수령을 별도로 허용합니다. 실행 전에 대상을 확인하세요.</p><form onsubmit="scopeMissions26(event)"><div class="formgrid"><label>대상 범위<select name="scope">${opts({student:'특정 학생',class:'특정 반',year:'학년도 전체'})}</select></label><label>학생<select name="studentId">${opts(Object.fromEntries(info.students.map(s=>[s.id,s.grade+'학년 '+s.classNo+'반 '+s.number+'번 '+s.name])))}</select></label><label>학년<input name="grade" type="number" value="2" min="1" max="6"></label><label>반<input name="classNo" type="number" value="1" min="1" max="99"></label><label>실행 기능<select name="action">${opts({reset_progress:'진행도만 초기화 — 재지급 없음',add_round:'추가 회차 부여 — 재수령 허용'})}</select></label><label>사유<input name="reason" minlength="2" maxlength="300" required></label></div><button class="primary">대상 확인 후 실행</button></form></section>`};
function presetMissions26(){if(!confirm('현재 편집 중인 초안을 일일3·주간3·월간3 기본안으로 바꿀까요? 저장·새 시작 전에는 학생 미션이 바뀌지 않습니다.'))return;const base={active:true,title:'',seconds:60,minRarity:'rare',reward:{card:null,pack:{packId:'basic',count:1}}};missionDraft25=[['daily','each_game',['beginner','intermediate'],1],['daily','complete',['connections.basic','beginner','intermediate','advanced'],3],['daily','packs',[],2],['weekly','complete',['speedrun','advanced'],5],['weekly','events',[],5],['weekly','attendance',[],3],['monthly','complete',['beginner','intermediate','advanced','speedrun'],20],['monthly','normal',[],20],['monthly','effects',[],2]].map(([period,type,games,target],i)=>({...copy(base),id:'preset26-'+i,period,type,games,target}));render()}
function scopeMissions26(e){e.preventDefault();const p=formData(e.target);p.schoolYear=year;const list=info.students.filter(s=>p.scope==='year'||p.scope==='student'&&s.id===p.studentId||p.scope==='class'&&s.grade===+p.grade&&s.classNo===+p.classNo),extra=p.action==='add_round';if(!list.length)return msg('대상 학생이 없습니다.');if(!confirm(`${year}학년도 ${list.length}명 (${list.slice(0,8).map(s=>s.name).join(', ')}${list.length>8?' 외':''})\n${extra?'새 회차를 부여하고 보상 재수령을 허용':'진행도만 초기화, 수령 보상 재지급 없음'}할까요?`))return;p.confirmed=true;p.allowReward=extra;task(async()=>{const r=await API.request('teacher.missions.scope',p);await refresh();msg(r.changed+'명의 미션 상태를 변경했습니다.')})}
// Historical disabled modes remain available only when inspecting old rankings.
const rankingBase26=ranking;ranking=function(){return rankingBase26().replace('</select></label><label>기간','<option value="challenge">도전 (이전 기록만)</option><option value="faceoff">페이스오프 (이전 기록만)</option></select></label><label>기간')};
